# Generated by Django 5.2.7 on 2025-11-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unidades', models.PositiveIntegerField(verbose_name='Unidades')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Presupuesto')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
        ),
    ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'APP',  # Tu aplicación personalizada
]
