# Generated by Django 5.2.7 on 2025-11-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
    ]
